# Generated by Django 5.2 on 2025-05-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantimage',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
